apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: onp-l2-address-pool
  namespace: metallb-system
spec:
  protocol: layer2
  addresses:
  - 192.168.123.50-192.168.123.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
   - onp-l2-address-pool
