apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: <network>-<node>-ethernet
spec:
  nodeSelector: 
    kubernetes.io/hostname: <hostname>
  desiredState:
    interfaces:
      - name: enp7s0
        description: Configure enp7s0
        type: ethernet
        state: up
        ipv4:
          dhcp: false
          address:
          - ip: 192.168.124.3
            prefix-length: 24
          enabled: true
    routes:
      config:
        - destination: 0.0.0.0/0
          metric: 115
          next-hop-address: 192.168.124.2
          next-hop-interface: enp7s0
          table-id: 254
