apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master0-br0
spec:
  nodeSelector: 
    kubernetes.io/hostname: master0
  maxUnavailable: 3 
  desiredState:
    interfaces:
      - name: br0
        description: Linux bridge with enp8s0 as a port 
        type: linux-bridge
        state: up
        ipv4:
          dhcp: false
          address:
          - ip: 192.168.124.2
            prefix-length: 24
          enabled: true
          auto-dns: false
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp8s0
    routes:
      config:
        - destination: 192.168.124.0/24
          metric: 1
          next-hop-address: 192.168.124.1
          next-hop-interface: br0
          table-id: 254
