apiVersion: v1
kind: Namespace
metadata:
  name: ext-ip
---
apiVersion: v1
kind: Pod
metadata:
  name: ext-ip
  namespace: ext-ip
  labels:
    app: ext-ip
spec:
  containers:
  - image: gcr.io/google_containers/echoserver:1.0
    imagePullPolicy: Always
    name: ext-ip
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ext-ip
  namespace: ext-ip
spec:
  externalIPs:
  - 192.168.126.10
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ext-ip
  type: LoadBalancer
