apiVersion: v1
kind: Service
metadata:
  name: metallb-router-internal-non-default
  namespace: openshift-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 81
  - name: https
    port: 443
    protocol: TCP
    targetPort: 444
  - name: metrics
    port: 1936
    protocol: TCP
    targetPort: 1937
  selector:
      ingresscontroller.operator.openshift.io/deployment-ingresscontroller: non-default
  type: LoadBalancer
