apiVersion: v1
kind: Service
metadata:
  name: metallb-apiserver
  namespace: openshift-kube-apiserver
spec:
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: openshift-kube-apiserver
  type: LoadBalancer
