apiVersion: v1
kind: Namespace
metadata:
  name: onp-metallb
---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  namespace: onp-metallb
  labels:
    app: echoserver
spec:
  containers:
  - image: registry.k8s.io/echoserver:1.0
    imagePullPolicy: Always
    name: echoserver
    ports:
    - containerPort: 8080
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: onp-metallb
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
  type: LoadBalancer
