apiVersion: v1
kind: Namespace
metadata:
  name: mlb
---
apiVersion: v1
kind: Pod
metadata:
  name: mlb
  namespace: mlb
  labels:
    app: mlb
spec:
  containers:
  - image: gcr.io/google_containers/echoserver:1.0
    imagePullPolicy: Always
    name: mlb
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mlb
  namespace: mlb
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mlb
  type: LoadBalancer
