apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: onp-nad-static
  namespace: onp-multus
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "onp-macvlan-bridge-static",
      "type": "macvlan",
      "capabilities": { "ips": true },
      "linkInContainer": true,
      "master": "enp8s0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
