apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: onp-multus-nad
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "onp-macvlan-whereabout",
      "type": "macvlan",
      "master": "enp8s0",
      "mode": "private",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.124.0/24",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.124.1",
        "exclude": [
           "192.168.124.1/32",
           "192.168.124.2/32",
           "192.168.124.3/32",
           "192.168.124.4/32"
        ]
      }
    }
