apiVersion: v1
kind: Pod
metadata:
  name: onp-multus-pod
  namespace: onp-multus
  annotations:
    k8s.v1.cni.cncf.io/networks: onp-multus
spec:
  containers:
  - name: onp-multus-container
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: quay.io/onp/onp-tools
  nodeSelector:
    kubernetes.io/hostname: master2.ocp.example.local
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
