apiVersion: v1
kind: Pod
metadata:
  name: onp-nad-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "onp-nad-static",
          "namespace": "onp-multus",
          "ips": [ "192.168.124.90/24" ]
        }
      ]
spec:
  containers:
  - name: onp-multus-container
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: quay.io/onp/onp-tools
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
